/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author acull
 */
public class VPrincipal extends javax.swing.JFrame {

    aplicacion.FachadaAplicacion fa;
    
    /**
     * Creates new form VPrincipal
     * @param fa
     */
    public VPrincipal(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        personalB = new javax.swing.JButton();
        especimenesB = new javax.swing.JButton();
        especiesB = new javax.swing.JButton();
        habitatsB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        personalB.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        personalB.setText("PERSONAL");
        personalB.setMaximumSize(new java.awt.Dimension(500, 500));
        personalB.setPreferredSize(new java.awt.Dimension(400, 250));

        especimenesB.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        especimenesB.setText("ESPECÍMENES");
        especimenesB.setMaximumSize(new java.awt.Dimension(500, 500));
        especimenesB.setPreferredSize(new java.awt.Dimension(400, 250));
        especimenesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especimenesBActionPerformed(evt);
            }
        });

        especiesB.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        especiesB.setText("ESPECIES");
        especiesB.setMaximumSize(new java.awt.Dimension(500, 500));
        especiesB.setPreferredSize(new java.awt.Dimension(400, 250));
        especiesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especiesBActionPerformed(evt);
            }
        });

        habitatsB.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        habitatsB.setText("HÁBITATS");
        habitatsB.setMaximumSize(new java.awt.Dimension(500, 500));
        habitatsB.setPreferredSize(new java.awt.Dimension(400, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personalB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(especiesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(especimenesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(habitatsB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(especimenesB, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(personalB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habitatsB, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(especiesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void especimenesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especimenesBActionPerformed
        // TODO add your handling code here:
        fa.visualizarEspecimenes(this);
    }//GEN-LAST:event_especimenesBActionPerformed

    private void especiesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especiesBActionPerformed
        // TODO add your handling code here:
        fa.visualizarEspecies(this);
    }//GEN-LAST:event_especiesBActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton especiesB;
    private javax.swing.JButton especimenesB;
    private javax.swing.JButton habitatsB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton personalB;
    // End of variables declaration//GEN-END:variables
}
