/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.FachadaAplicacion;

/**
 *
 * @author aculledor
 */
public class VRiesgosDePropMag extends javax.swing.JDialog {
    private VPrincipal padre;
    private FachadaAplicacion fa;
    private ModeloListaStrings mListaAsoc;
    private ModeloListaStrings mListaDes;
    private String propMag;

    /**
     * Creates new form VRiesgosDePropMag
     */
    public VRiesgosDePropMag(java.awt.Frame parent, aplicacion.FachadaAplicacion fa, String propMag) {
        super(parent);
        this.fa = fa;
        initComponents();
        this.padre = (VPrincipal) parent;
        this.propMag = propMag;
        
        //Nombre de la propiedad magica
        labNombre.setText(this.propMag);
        
        //Riesgos que SI tiene
        mListaAsoc = new ModeloListaStrings();
        lstAsoc.setModel(mListaAsoc);
        mListaAsoc.setElementos(this.fa.getListaRiesgosAsoc(this.propMag));
        if (mListaAsoc.getSize() > 0) {
            lstAsoc.setSelectedIndex(0);
            desasociarB.setEnabled(true);
        } else {
            desasociarB.setEnabled(false);
        }

        //Riesgos que NO tiene
        mListaDes= new ModeloListaStrings();
        lstDes.setModel(mListaDes);
        mListaDes.setElementos(this.fa.getListaRiesgosDes(this.propMag));
        if (mListaDes.getSize() > 0) {
            lstDes.setSelectedIndex(0);
            asociarB.setEnabled(true);
        } else {
            asociarB.setEnabled(false);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAsoc = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDes = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        desasociarB = new javax.swing.JButton();
        asociarB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        actualizarB = new javax.swing.JButton();
        salirB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labNombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labNombre.setText("NOMBRE PROP MAG");
        labNombre.setToolTipText("");

        lstAsoc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lstAsoc.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstAsoc);

        lstDes.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lstDes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstDes);

        desasociarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaD.jpg"))); // NOI18N
        desasociarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desasociarBActionPerformed(evt);
            }
        });

        asociarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/flechaI.jpg"))); // NOI18N
        asociarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asociarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(asociarB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desasociarB, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(desasociarB, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(asociarB, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Riesgos asignados");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Riesgos sin asignar");

        actualizarB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        actualizarB.setText("ACTUALIZAR");
        actualizarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBActionPerformed(evt);
            }
        });

        salirB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        salirB.setText("SALIR");
        salirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(actualizarB, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirB, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addGap(50, 50, 50)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)))
                    .addComponent(labNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(actualizarB, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(salirB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desasociarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desasociarBActionPerformed
        // TODO add your handling code here:
        ModeloListaStrings mRC;
        ModeloListaStrings mC;

        mRC = (ModeloListaStrings) lstDes.getModel();
        mC = (ModeloListaStrings) lstAsoc.getModel();
        mRC.nuevoElemento(mC.getElementAt(lstAsoc.getSelectedIndex()));
        mC.borrarElemento(lstAsoc.getSelectedIndex());
        if (mC.getSize() == 0) {
            desasociarB.setEnabled(false);
        } else {
            lstAsoc.setSelectedIndex(0);
        }
        lstDes.setSelectedIndex(mRC.getSize() - 1);
        asociarB.setEnabled(true);
    }//GEN-LAST:event_desasociarBActionPerformed

    private void asociarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asociarBActionPerformed
        // TODO add your handling code here:
        ModeloListaStrings mRC;
        ModeloListaStrings mC;

        mRC = (ModeloListaStrings) lstDes.getModel();
        mC = (ModeloListaStrings) lstAsoc.getModel();
        mC.nuevoElemento(mRC.getElementAt(lstDes.getSelectedIndex()));
        mRC.borrarElemento(lstDes.getSelectedIndex());
        if (mRC.getSize() == 0) {
            asociarB.setEnabled(false);
        } else {
            lstDes.setSelectedIndex(0);
        }
        lstAsoc.setSelectedIndex(mC.getSize() - 1);
        desasociarB.setEnabled(true);
    }//GEN-LAST:event_asociarBActionPerformed

    private void salirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBActionPerformed
        // TODO add your handling code here:
        fa.asignarRiesgos(propMag, mListaAsoc.getElementos());
        this.dispose();
    }//GEN-LAST:event_salirBActionPerformed

    private void actualizarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBActionPerformed
        // TODO add your handling code here:
        fa.asignarRiesgos(propMag, mListaAsoc.getElementos());
        
        mListaAsoc.setElementos(this.fa.getListaRiesgosAsoc(this.propMag));
        mListaDes.setElementos(this.fa.getListaRiesgosDes(this.propMag));
        if (mListaAsoc.getSize() > 0) {
            lstAsoc.setSelectedIndex(0);
            desasociarB.setEnabled(true);
        }
        if (mListaDes.getSize() > 0) {
            asociarB.setEnabled(true);
        }
    }//GEN-LAST:event_actualizarBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarB;
    private javax.swing.JButton asociarB;
    private javax.swing.JButton desasociarB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labNombre;
    private javax.swing.JList<String> lstAsoc;
    private javax.swing.JList<String> lstDes;
    private javax.swing.JButton salirB;
    // End of variables declaration//GEN-END:variables
}
